Basic folder structure
skateray17/ExadelBackEndFoodTask pull request #3
Opened 2018-04-12 13:06 UTC by skateray17

2018-04-12 14:24 UTC, armenbadalyan requested changes

2018-04-12 14:24 UTC, armenbadalyan commented on src/app.js
> +const dbName = 'FoodDelivery';
Instead of hardcoding the connection details it's recommended to keep them in .env files. See https://github.com/motdotla/dotenv

2018-04-13 14:20 UTC, Karabanovich approved these changes

2018-04-13 14:35 UTC, armenbadalyan approved these changes

2018-04-13 14:35 UTC, merged